import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topbar from "../components/Topbar";
import Rightbar from "../components/Rightbar";
import { AuthProvider } from "../context/AuthContext";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const showRightbar = pathname !== "/messages";
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <AuthProvider>
          <Topbar />
          <div className="flex justify-center min-h-screen pt-4">
            <main className="w-full max-w-xl flex flex-col items-center px-2">{children}</main>
            {showRightbar && <div className="hidden lg:block"><Rightbar /></div>}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
