"""updated the post model by adding the picture and vidoes section

Revision ID: fa04955f586b
Revises: 8eb86c02f78e
Create Date: 2025-06-18 15:28:06.545772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa04955f586b'
down_revision: Union[str, None] = '8eb86c02f78e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('video_url', sa.String(), nullable=True))
    op.alter_column('posts', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('posts', 'video_url')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
